import FlightsHeader from "@/components/flghts/FlightsHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Flights:page",
  description: "Generated by Vaidik Singh Nirwan",
};

export default function FlightsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className={`antialiased `}
      >
        <div className="border-b-[1px] border-gray-200">
            {/* header Section */}
            <FlightsHeader/>
        </div>
        <div>
            {children}
        </div>
      </div>
  );
}
